name: Build C++ Project

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
         - uses: actions/checkout@v2

         - name: Set up CMake
           run: cmake -B build

         - name: Build
           run: cmake --build build
